### ISSUE TITLE
Implicit Templates Example

### ISSUE THREAD

**Issue by shawnwanderson** [spapas/generic-scaffold-demo#1]
It would be nice to see and example of the implicit templates with the template tags.

**Comment by spapas** [comment]
Hello @shawnwanderson , I recommend taking a look at the fall-back templates on https://github.com/spapas/django-generic-scaffold/tree/master/generic_scaffold/templates/generic_scaffold

Just copy them (list.html, detail.html, form.html and confirm_delete.html) to the templates folder of your app with the correct names (appname/modelname_form.html etc) and you should be ready to go. For example, the fall-back list template is the following:

```
{% extends 'generic_scaffold/base.html' %}
{% load generic_scaffold_tags %}
{% block content %}
<!-- Don't forget to use your own base.html -->

<a href='{% url object_list.model.create_url_name %}'>Create</a>
<ul>
    {% for object in object_list %}
        <li>
            {{ object }}
            <a href='{% url object.detail_url_name object.id %}'>detail</a>
            <a href='{% url object.update_url_name object.id %}'>update</a>
            <a href='{% url object.delete_url_name object.id %}'>delete</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}
```

Now, this uses a non-documented API (``object.action_url_name``) instead of the proposed one (``set_urls_for_scaffold``) -- please avoid using it. Instead use the proposed one like this:

```
{% set_urls_for_scaffold prefix="myprefix" as urls %}
<a href='{% url urls.create %}'>Create </a>
<a href='{% url urls.detail object.id%}'>Detail</a>
etc
```

**Comment by shawnwanderson** [comment]
Thank you very much spapas. This is what I ended up doing.

**Comment by spapas** [comment]
Great!
